# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: app2
#   namespace: cluster-config
# spec:
#   interval: 5m
#   url: https://github.com/davidxw/gitops-demo-app2
#   ref:
#     branch: main
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: app2
#   namespace: cluster-config
# spec:
#   interval: 1m
#   targetNamespace: app2
#   sourceRef:
#     kind: GitRepository
#     name: app2
#   path: "./manifests"
#   prune: true